# Gitpod setup
image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: npm install
    command: cd functions
    command: npm install
    command: cd ..
    command: firebase login --no-localhost
