# Gitpod setup
image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: 
      echo 'init script' echo "Getting dependencies..." 
      & npm install
      & cd functions
      & npm install 
      & firebase-functions@latest firebase-admin@latest --save 
      & cd ..
  - command:
      firebase login --no-localhost
